// generated by ChatGP //
const isValidEmail = (email) => {
    // Regular expression to match an email
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    // Check if the email matches the regular expression
    return emailRegex.test(email);
}


module.exports = { isValidEmail }